name: Cron

on:
   schedule:
     - cron: '0 */12 * * *'

jobs:
  test:
    name: PHP ${{ matrix.php_version }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: cache
        key: ${{ runner.os }}-php
        restore-keys: |
          ${{ runner.os }}-php

    - name: Update
      run: php ./bin/build.php
      env:
        TOKEN: ${{ secrets.TOKEN }}
        ACTOR: ${{ secrets.ACTOR }}
        REPO_SLUG: ${{ secrets.REPO_SLUG }}
        
  activity:
    name: Keep repo active
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v2
      with:
         head: ${{ secrets.ACTIVE_REF }}
    - run: date > latest
    - run: |
        git config --local user.email "${{ secrets.ACTOR }}"
        git commit -m "Add changes" -a
    - uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: ${{ secrets.ACTIVE_REF }}
